export const WORDS = [
  "AGENT",
  "WORLD",
  "ABOUT",
  "HEART",
  "WATER",
  "SIXTY",
  "BOARD",
  "MONTH",
  "MUSIC",
  "PARTY",
  "PIANO",
  "MOUTH",
  "WOMAN",
  "SUGAR",
  "AMBER",
  "DREAM",
  "LAUGH",
  "TIGER",
  "EARTH",
  "MONEY",
  "WORDS",
  "SMILE",
  "LEMON",
  "SOUTH",
  "AFTER",
  "STONE",
  "THING",
  "LIGHT",
  "STORY",
  "POWER",
  "TODAY",
  "RANGE",
  "PEARL",
  "VENOM",
  "PROXY",
  "ROUND",
  "HOVER",
  "CANDY",
  "ABOVE",
  "PHONE",
  "OTHER",
  "SMART",
  "BLACK",
  "MAGIC",
  "FRUIT",
  "RADIO",
  "ROYAL",
  "HONEY",
  "FLAKE",
  "SOUND",
];

export enum KeyStatus {
  NONE = 0,
  NO = 1,
  KINDA = 2,
  YES = 3,
}

export type KeyMeta = { rowIdx: number; status: KeyStatus; isActive: boolean };
export const keys: Record<string, KeyMeta> = {
  q: { rowIdx: 0, status: KeyStatus.NONE, isActive: false },
  w: { rowIdx: 0, status: KeyStatus.NONE, isActive: false },
  e: { rowIdx: 0, status: KeyStatus.NONE, isActive: false },
  r: { rowIdx: 0, status: KeyStatus.NONE, isActive: false },
  t: { rowIdx: 0, status: KeyStatus.NONE, isActive: false },
  y: { rowIdx: 0, status: KeyStatus.NONE, isActive: false },
  u: { rowIdx: 0, status: KeyStatus.NONE, isActive: false },
  i: { rowIdx: 0, status: KeyStatus.NONE, isActive: false },
  o: { rowIdx: 0, status: KeyStatus.NONE, isActive: false },
  p: { rowIdx: 0, status: KeyStatus.NONE, isActive: false },

  a: { rowIdx: 1, status: KeyStatus.NONE, isActive: false },
  s: { rowIdx: 1, status: KeyStatus.NONE, isActive: false },
  d: { rowIdx: 1, status: KeyStatus.NONE, isActive: false },
  f: { rowIdx: 1, status: KeyStatus.NONE, isActive: false },
  g: { rowIdx: 1, status: KeyStatus.NONE, isActive: false },
  h: { rowIdx: 1, status: KeyStatus.NONE, isActive: false },
  j: { rowIdx: 1, status: KeyStatus.NONE, isActive: false },
  k: { rowIdx: 1, status: KeyStatus.NONE, isActive: false },
  l: { rowIdx: 1, status: KeyStatus.NONE, isActive: false },

  z: { rowIdx: 2, status: KeyStatus.NONE, isActive: false },
  x: { rowIdx: 2, status: KeyStatus.NONE, isActive: false },
  c: { rowIdx: 2, status: KeyStatus.NONE, isActive: false },
  v: { rowIdx: 2, status: KeyStatus.NONE, isActive: false },
  b: { rowIdx: 2, status: KeyStatus.NONE, isActive: false },
  n: { rowIdx: 2, status: KeyStatus.NONE, isActive: false },
  m: { rowIdx: 2, status: KeyStatus.NONE, isActive: false },
};
